-- ===================================================
-- CAMPUS CASH - Smart Digital Campus Wallet Database Schema
-- Compatible with MySQL 8.0+ and SQLite 3
-- ===================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL CHECK(role IN ('STUDENT', 'PARENT', 'VENDOR', 'ADMIN')),
  phone VARCHAR(50),
  avatar VARCHAR(255),
  status VARCHAR(20) DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE', 'DISABLED', 'PENDING')),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. STUDENTS TABLE
CREATE TABLE IF NOT EXISTS students (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER UNIQUE NOT NULL,
  roll_number VARCHAR(100) UNIQUE NOT NULL,
  department VARCHAR(100),
  year_of_study INTEGER,
  parent_id INTEGER,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 3. PARENTS TABLE
CREATE TABLE IF NOT EXISTS parents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER UNIQUE NOT NULL,
  relationship VARCHAR(50) DEFAULT 'Parent',
  emergency_contact VARCHAR(50),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 4. VENDORS TABLE
CREATE TABLE IF NOT EXISTS vendors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER UNIQUE NOT NULL,
  business_name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL, -- Canteen, Stationery, Printing, Transport, Books, Store
  location VARCHAR(255),
  is_approved BOOLEAN DEFAULT 1,
  qr_code_id VARCHAR(100) UNIQUE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 5. ADMINS TABLE
CREATE TABLE IF NOT EXISTS admins (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER UNIQUE NOT NULL,
  department VARCHAR(100),
  designation VARCHAR(100),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 6. WALLETS TABLE
CREATE TABLE IF NOT EXISTS wallets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER UNIQUE NOT NULL,
  balance DECIMAL(12,2) NOT NULL DEFAULT 0.00 CHECK(balance >= 0),
  currency VARCHAR(10) DEFAULT 'INR',
  status VARCHAR(20) DEFAULT 'ACTIVE',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 7. WALLET TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  transaction_id VARCHAR(100) UNIQUE NOT NULL,
  wallet_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  type VARCHAR(50) NOT NULL CHECK(type IN ('RECHARGE', 'PAYMENT', 'REFUND', 'REWARD_CREDIT')),
  amount DECIMAL(12,2) NOT NULL,
  previous_balance DECIMAL(12,2) NOT NULL,
  new_balance DECIMAL(12,2) NOT NULL,
  reference_id VARCHAR(100),
  status VARCHAR(20) NOT NULL CHECK(status IN ('SUCCESS', 'PENDING', 'FAILED', 'REFUNDED')),
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (wallet_id) REFERENCES wallets(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 8. PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  payment_id VARCHAR(100) UNIQUE NOT NULL,
  transaction_id VARCHAR(100) UNIQUE NOT NULL,
  student_id INTEGER NOT NULL,
  vendor_id INTEGER NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  category VARCHAR(100) DEFAULT 'Food',
  status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (student_id) REFERENCES users(id),
  FOREIGN KEY (vendor_id) REFERENCES users(id),
  FOREIGN KEY (transaction_id) REFERENCES wallet_transactions(transaction_id)
);

-- 9. QR CODES TABLE
CREATE TABLE IF NOT EXISTS qr_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  qr_id VARCHAR(100) UNIQUE NOT NULL,
  vendor_id INTEGER NOT NULL,
  vendor_name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  fixed_amount DECIMAL(12,2) DEFAULT NULL,
  is_active BOOLEAN DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (vendor_id) REFERENCES users(id)
);

-- 10. NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  category VARCHAR(50) NOT NULL CHECK(category IN ('Payment', 'Recharge', 'Warning', 'Reward', 'System')),
  is_read BOOLEAN DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 11. REWARD POINTS TABLE
CREATE TABLE IF NOT EXISTS reward_points (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_id INTEGER UNIQUE NOT NULL,
  points_balance INTEGER NOT NULL DEFAULT 0,
  lifetime_points INTEGER NOT NULL DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 12. REWARDS CATALOG TABLE
CREATE TABLE IF NOT EXISTS rewards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  points_required INTEGER NOT NULL,
  reward_code VARCHAR(100) UNIQUE,
  category VARCHAR(100),
  is_active BOOLEAN DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 13. REWARD REDEMPTIONS TABLE
CREATE TABLE IF NOT EXISTS reward_redemptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_id INTEGER NOT NULL,
  reward_id INTEGER NOT NULL,
  points_spent INTEGER NOT NULL,
  status VARCHAR(20) DEFAULT 'REDEEMED',
  redeemed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (student_id) REFERENCES users(id),
  FOREIGN KEY (reward_id) REFERENCES rewards(id)
);

-- 14. SPENDING LIMITS TABLE
CREATE TABLE IF NOT EXISTS spending_limits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_id INTEGER UNIQUE NOT NULL,
  parent_id INTEGER NOT NULL,
  daily_limit DECIMAL(12,2) DEFAULT 500.00,
  weekly_limit DECIMAL(12,2) DEFAULT 2500.00,
  monthly_limit DECIMAL(12,2) DEFAULT 5000.00,
  action_on_exceed VARCHAR(20) DEFAULT 'WARNING' CHECK(action_on_exceed IN ('WARNING', 'BLOCK')),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 15. EXPENSE CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS expense_categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) UNIQUE NOT NULL,
  icon VARCHAR(50),
  color VARCHAR(20)
);

-- 16. AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  user_email VARCHAR(255),
  role VARCHAR(50),
  action VARCHAR(255) NOT NULL,
  module VARCHAR(100) NOT NULL,
  ip_address VARCHAR(100) DEFAULT '127.0.0.1',
  status VARCHAR(50) DEFAULT 'SUCCESS',
  details TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
